spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-t?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: 'root'
    password: 'gnpp0310'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
